### PR TITLE
Add optional fixed length to lists

### LINKED ISSUE #181: Fixed length arrays
Rust has fixed length arrays whose type is written as `[u8;32]` for a 32-byte array. You can achieve this in the current wit specification by doing `tuple<u8,u8 ... u8>` (with 32 `u8`s). Could `list<u8,32>` or something be a first class type to avoid abusing tuples in this way even if it desugars to something similar?

### PR DESCRIPTION
**Pull request by cpetig**
Resolves #181

### CODE REVIEW

**Comment by jeffparsons** [comment]
Question from the peanut gallery: 

Has this change been approved in principle already — i.e. is it just the implementation that's awaiting review?

**Comment by lukewagner** [comment]
Yes, I think I've heard broad agreement on this feature.  But it is a good question of why not just merge the PR now, given that it's emoji-gated (so that it's clear it's not implemented everywhere) and not controversial.  That's probably a good idea, so I'll do that next week unless anyone suggests otherwise.

**Comment by lukewagner** [comment]
Rereading the PR just now, it seems like we'd want a low (but relaxable in the future) upper bound on the fixed length so that bindings generators don't have to think about rare pathological cases (similar to what we did for `flags`).  Maybe 16?

**Comment by jeffparsons** [comment]
I'd argue for at least 64 to support the largest variants of SHA-2, SHA-3 and BLAKE3, which are all 512 bits, as `list<u8, 64>`.

I know this is a very narrow use case, but most of the others that are on my radar are smaller arrays, e.g., IPv6, UUID, coordinates and color values for "graphics stuff", etc.

**Comment by lukewagner** [comment]
Yes, that's a good point.  Given that I'm overdue from merging after my previous comment and this is a minor refinement, I'll merge this PR now as-is and file a new PR to add the length limits in a bit, and we can agree on 64 or whatever else there.

**Pull request merged**
